# Generated by Django 3.0.4 on 2020-03-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passapplication',
            name='status',
            field=models.CharField(choices=[('Not', 'Not Seen'), ('Reject', 'Rejected'), ('Held', 'With Held'), ('Approve', 'Approved')], default='Not', max_length=50, verbose_name='Status Of Application'),
        ),
    ]
