# Generated by Django 3.0.4 on 2020-03-28 07:24

import Pass.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pass', '0003_passapplication_requestedauthority'),
    ]

    operations = [
        migrations.AddField(
            model_name='passapplication',
            name='AadharCardBUrl',
            field=models.URLField(blank=True, null=True, verbose_name='Adhar Card Front Url'),
        ),
        migrations.AddField(
            model_name='passapplication',
            name='AadharCardFUrl',
            field=models.URLField(blank=True, null=True, verbose_name='Adhar Card Front Url'),
        ),
        migrations.AddField(
            model_name='passapplication',
            name='recentPictureUrl',
            field=models.URLField(blank=True, null=True, verbose_name='Adhar Card Front Url'),
        ),
        migrations.AlterField(
            model_name='passapplication',
            name='AadharCardB',
            field=models.ImageField(blank=True, null=True, upload_to=Pass.models.uploadAdharBack, verbose_name='Aadhar Card Back'),
        ),
        migrations.AlterField(
            model_name='passapplication',
            name='AadharCardF',
            field=models.ImageField(blank=True, null=True, upload_to=Pass.models.uploadAdharFront, verbose_name='Aadhar Card Front'),
        ),
        migrations.AlterField(
            model_name='passapplication',
            name='recentPicture',
            field=models.ImageField(blank=True, null=True, upload_to=Pass.models.uploadProfilePicture, verbose_name='Profile Picture'),
        ),
    ]
