# Generated by Django 3.0.4 on 2020-03-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pass', '0004_auto_20200328_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='passapplication',
            name='valid',
            field=models.BooleanField(default=False, help_text='The Validity of Pass', verbose_name='Vaild'),
        ),
    ]
