# Generated by Django 3.0.4 on 2020-03-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0001_initial'),
        ('Pass', '0006_auto_20200328_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passapplication',
            name='requestedAuthority',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='AuthorityApplications', to='Authority.Authorizer', verbose_name='Requested Authority'),
        ),
    ]
