# Generated by Django 3.0.4 on 2020-03-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pass', '0007_auto_20200328_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='passapplication',
            name='district',
            field=models.CharField(default='', max_length=60, verbose_name='Applying District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passapplication',
            name='workstation',
            field=models.CharField(default='', max_length=100, verbose_name='Workstation'),
            preserve_default=False,
        ),
    ]
