# Generated by Django 3.0.4 on 2020-03-29 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pass', '0008_auto_20200328_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='passapplication',
            name='endtdatetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiry of pass'),
        ),
        migrations.AddField(
            model_name='passapplication',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 10, 55, 14, 691844, tzinfo=utc), verbose_name='Outing Start Time'),
            preserve_default=False,
        ),
    ]
