# Generated by Django 3.0.4 on 2020-03-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='AadharCardNo',
            field=models.CharField(blank=True, max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='Aadhar Card No'),
        ),
    ]
