# Generated by Django 3.0.4 on 2020-03-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0002_auto_20200328_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='district',
            field=models.CharField(default='', max_length=60, verbose_name='Applying District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='workstation',
            field=models.CharField(default='', max_length=100, verbose_name='Workstation'),
            preserve_default=False,
        ),
    ]
