# Generated by Django 3.0.4 on 2020-03-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0003_auto_20200328_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phoneNumber',
            field=models.CharField(max_length=10, unique=True, verbose_name='Phone Number'),
        ),
    ]
