# Generated by Django 3.0.4 on 2020-03-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckUpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(help_text='It Include The Full name OF The Person', max_length=120, verbose_name='Full Name')),
                ('symtoms', models.TextField(blank=True, help_text='Note CSV Format', null=True, verbose_name='Sysmtoms Requested')),
                ('addr', models.TextField(blank=True, help_text='Address of the Person', null=True, verbose_name='Address')),
                ('phoneNumber', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('district', models.CharField(max_length=60, verbose_name='Applying District')),
                ('block', models.CharField(max_length=60, verbose_name='Applying Block')),
                ('cityVillage', models.CharField(max_length=60, verbose_name='Applying City/Village')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='Applied when')),
                ('status', models.CharField(choices=[('Not', 'Not Seen'), ('Pend', 'Pending'), ('Checked', 'Checked')], default='Not', max_length=50, verbose_name='Status Of Request')),
                ('checkedPerson', models.CharField(help_text='Checked Person', max_length=120, verbose_name='Checked Person')),
                ('send', models.BooleanField(default=False, help_text='Team Send To Check', verbose_name='Send')),
            ],
            options={
                'verbose_name': 'CheckUpRequest',
                'verbose_name_plural': 'CheckUpRequests',
            },
        ),
    ]
