# Generated by Django 3.0.4 on 2020-03-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authority', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizer',
            name='typE',
            field=models.CharField(choices=[('DM', 'District Magistate'), ('EM', 'Executive Magistate'), ('HC', 'Health Department')], default='EM', max_length=50, verbose_name='Type Of Account'),
        ),
    ]
