# Generated by Django 3.0.4 on 2020-03-28 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onduty',
            options={'verbose_name': 'On Duty', 'verbose_name_plural': 'On Dutys'},
        ),
        migrations.CreateModel(
            name='OnDutyChecked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passIds', models.TextField(blank=True, help_text='Note CSV Format', null=True, verbose_name='Enter the Pass Id')),
                ('date', models.DateField(verbose_name='Date')),
                ('checker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OnDutyCheckedPass', to='Checker.OnDuty', verbose_name='Checked Authority')),
            ],
            options={
                'verbose_name': 'On Duty Checked',
                'verbose_name_plural': 'On Duty Checkeds',
            },
        ),
    ]
