# Generated by Django 3.0.4 on 2020-03-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checker', '0002_auto_20200328_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='onduty',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='onduty',
            name='phoneNumber',
            field=models.CharField(default=1, max_length=10, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
