# Generated by Django 3.0.4 on 2020-03-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checker', '0003_auto_20200328_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ondutychecked',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
